services:
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    hostname: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    hostname: loansdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    hostname: cardsdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: masthansoma/configserver:v2
    container_name: configserver-ms
    ports:
      - "8888:8888"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: masthansoma/accounts:v2
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=accounts
      - SPRING_DATASOURCE_URL=jdbc:mysql://accountsdb:3306/accountsdb
    extends:
      file: common-config.yml
      service: microservice-configserver-service

  loans:
    image: masthansoma/loans:v2
    container_name: loans-ms
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=loans
      - SPRING_DATASOURCE_URL=jdbc:mysql://loansdb:3306/loansdb
    extends:
      file: common-config.yml
      service: microservice-configserver-service

  cards:
    image: masthansoma/cards:v2
    container_name: cards-ms
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    environment:
      - SPRING_APPLICATION_NAME=cards
      - SPRING_DATASOURCE_URL=jdbc:mysql://cardsdb:3306/cardsdb
    extends:
      file: common-config.yml
      service: microservice-configserver-service

networks:
  eazybank:
    driver: bridge